//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : StaticData.cpp
//  @ Date : 2017/9/29
//  @ Author : 
//
//


#include "StaticData.h"

StaticData StaticData::sharedStaticData() {

}

void StaticData::purge() {

}

int StaticData::intValueForKey(std::string Key) {

}

char StaticData::stringValueFromKey(int Key) {

}

float StaticData::floatValueFromKey(int Key) {

}

bool StaticData::booleanFromKey(int Key) {

}

cocos2d::CCPoint StaticData::pointFromKey(int Key) {

}

cocos2d::CCRect StaticData::rectFromKey(int Key) {

}

cocos2d::CCSize StaticData::sizeFromKey(int Key) {

}

bool StaticData::init() {

}

StaticData::~StaticData() {

}

StaticData::StaticData() {

}

