//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : StaticData.h
//  @ Date : 2017/9/29
//  @ Author : 
//
//


#if !defined(_STATICDATA_H)
#define _STATICDATA_H


class StaticData {
public:
	std::string _staticFileName;
	static StaticData sharedStaticData();
	static void purge();
	int intValueForKey(std::string Key);
	char stringValueFromKey(int Key);
	float floatValueFromKey(int Key);
	bool booleanFromKey(int Key);
	cocos2d::CCPoint pointFromKey(int Key);
	cocos2d::CCRect rectFromKey(int Key);
	cocos2d::CCSize sizeFromKey(int Key);
protected:
	cocos2d::CCDictionary _dictionary;
	bool init();
private:
	~StaticData();
	StaticData();
};

#endif  //_STATICDATA_H
